Repository IntelPython/sdc, pull requests merged in 2019-11, with the labels that each got.

#269 Add config for PEP8Speak
  .pep8speaks.yml
Labels: Ready for Review

#253 Add numba_pandas extension
  hpat/__init__.py
  setup.py
Labels: enhancement

#241 Implement Series.nsmallest()/Series.nlargest() in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/api.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#266 Prototype type validator for typing stage
  hpat/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#271 Fix docstring for nsmallest in new styte
  hpat/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#248 Series.argsort() / Series.sort_values()
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#273 Skip 3 tests on series.var() in old style
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#267 Refactor buildscripts
  .coveragerc
  .coveralls.yml
  .travis.yml
  azure-pipelines.yml
  buildscripts/azure-template-linux-macos.yml
  buildscripts/azure-template-windows.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/build.py
  buildscripts/build.sh
  buildscripts/code_style.sh
  buildscripts/h5py-conda-recipe/bld.bat
  buildscripts/h5py-conda-recipe/build.sh
  buildscripts/h5py-conda-recipe/conda_build_config.yaml
  buildscripts/h5py-conda-recipe/meta.yaml
  buildscripts/hdf5-parallel-conda-recipe/bld.bat
  buildscripts/hdf5-parallel-conda-recipe/build.sh
  buildscripts/hdf5-parallel-conda-recipe/meta.yaml
  buildscripts/hpat-conda-recipe/bld.bat
  buildscripts/hpat-conda-recipe/build.sh
  buildscripts/hpat-conda-recipe/meta.yaml
  buildscripts/hpat-conda-recipe/run_test.sh
  buildscripts/install_conda.bat
  buildscripts/install_conda.sh
  buildscripts/numba-conda-recipe/bld.bat
  buildscripts/numba-conda-recipe/build.sh
  buildscripts/numba-conda-recipe/license.txt
  buildscripts/numba-conda-recipe/meta.yaml
  buildscripts/parquet-reader-conda-recipe/bld.bat
  buildscripts/parquet-reader-conda-recipe/build.sh
  buildscripts/parquet-reader-conda-recipe/meta.yaml
  buildscripts/sdc-conda-recipe/bld.bat
  buildscripts/sdc-conda-recipe/build.sh
  buildscripts/sdc-conda-recipe/conda_build_config.yaml
  buildscripts/sdc-conda-recipe/meta.yaml
  buildscripts/sdc-conda-recipe/run_test.bat
  buildscripts/sdc-conda-recipe/run_test.sh
  buildscripts/sdc_pi_example.py
  buildscripts/setup_conda.sh
  buildscripts/test.py
  buildscripts/utilities.py
  hpat/tests/test_hiframes.py
  hpat/tests/test_io.py
Labels: Ready for Review

#238 Implementation Series.cov in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#262 Fix new-style implementation of Series.append() method
  hpat/datatypes/common_functions.py
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/api.py
  hpat/hiframes/pd_series_ext.py
  hpat/str_arr_ext.py
  hpat/tests/test_series.py
Labels: Waiting on author

#268 Series.value_counts() in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready to merge

#279 fix for argsort/sort_values indices check
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/tests/test_series.py
Labels: Waiting on author

#122 Unicode string performance tests template
  hpat/runtests.py
  hpat/tests/__init__.py
  hpat/tests/test_utils.py
  hpat/tests/tests_perf/__init__.py
  hpat/tests/tests_perf/test_perf_series_str.py
  hpat/tests/tests_perf/test_perf_unicode.py
  hpat/tests/tests_perf/test_perf_utils.py
Labels: Ready to merge

#240 Implementation Seies.corr in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Waiting on author

#285 Fix windows scipy issue
  buildscripts/build.py
  buildscripts/sdc_pi_example.py
  buildscripts/test.py
  buildscripts/utilities.py
Labels: Ready for Review

#291 Series astype new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/hiframes/series_kernels.py
  hpat/tests/test_series.py
Labels: Waiting on CI

#264 Implement Series.pct_change() in a new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#257 pandas.core.strings.StringMethods functions type
  hpat/datatypes/__init__.py
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/datatypes/hpat_pandas_stringmethods_functions.py
  hpat/datatypes/hpat_pandas_stringmethods_types.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/str_ext.py
  hpat/tests/test_hiframes.py
  hpat/tests/test_series.py
Labels: Ready for Review

#298 Numba master build
  .travis.yml
  azure-pipelines.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/build.py
  buildscripts/numba-conda-recipe/LICENSE.txt
  buildscripts/numba-conda-recipe/README.md
  buildscripts/numba-conda-recipe/recipe/bld.bat
  buildscripts/numba-conda-recipe/recipe/build.sh
  buildscripts/numba-conda-recipe/recipe/mandel.py
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  buildscripts/numba-conda-recipe/recipe/run_test.bat
  buildscripts/numba-conda-recipe/recipe/run_test.sh
  buildscripts/sdc_pi_example.py
  buildscripts/test.py
  buildscripts/utilities.py
Labels: Ready for Review, Waiting on CI

#303 Make approved usage for Intel(R) DAAL name
  sdc/distributed.py
  sdc/ml/naive_bayes.py
  sdc/ml/svc.py
Labels: Ready for Review, Waiting on CI

#302 Add README.md for performnace tests
  sdc/tests/tests_perf/README.md
  sdc/tests/tests_perf/test_perf_series_str.py
  sdc/tests/tests_perf/test_perf_unicode.py
  sdc/tests/tests_perf/test_perf_utils.py
Labels: Waiting on CI

#307 Move common code of perf.tests to separate place
  sdc/tests/tests_perf/test_perf_base.py
  sdc/tests/tests_perf/test_perf_series_str.py
  sdc/tests/tests_perf/test_perf_unicode.py
Labels: Waiting on CI

#306 Make coverage work
  .coveragerc
  README.rst
  buildscripts/test.py
Labels: Ready for Review, Waiting on CI

#311 Move strip methods to Numba pipeline
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Ready for Review

#310 Feature/tests perf
  sdc/tests/tests_perf/test_perf_utils.py
Labels: Ready for Review

#314 performance tests for series.min/max
  sdc/tests/test_utils.py
  sdc/tests/tests_perf/__init__.py
  sdc/tests/tests_perf/test_perf_series.py
  sdc/tests/tests_perf/test_perf_series_str.py
  sdc/tests/tests_perf/test_perf_unicode.py
  sdc/tests/tests_perf/test_perf_utils.py
Labels: Ready for Review

#316 Minor fix in generating data for some perf.tests
  sdc/tests/tests_perf/test_perf_series.py
  sdc/tests/tests_perf/test_perf_utils.py
Labels: Ready for Review

#319 Add automatic switch of pipeline for some methods
  sdc/hiframes/pd_series_ext.py
Labels: Ready for Review

#320 Add init of mpi in numba pipeline for perf.testing
  sdc/runtests.py
Labels: Ready for Review

#329 add perf tests
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#341 fix nunique
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#336 fix Series.count
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review
