Repository IntelPython/sdc, pull requests merged in 2019-10, with the labels that each got.

#190 Add 5 test cases
  tests_perf/tests/algorithms.py
  tests_perf/tests/data_generator.py
  tests_perf/tests/series.py
Labels: Performace tests

#196 Add perf test case run in separate proc
  tests_perf/__init__.py
  tests_perf/benchmark.py
  tests_perf/runner.py
Labels: Performace tests

#193 Update instructions for building from source on Windows.
  README.rst
Labels: Documentation

#167 Change tests failed due to int64 vs int32 dtype mismatch
  hpat/tests/test_dataframe.py
  hpat/tests/test_hpat_jit.py
  hpat/tests/test_series.py
Labels: [WIP] Work in progress, question

#213 Unboxing for pandas Int64Index and RangeIndex
  hpat/hiframes/boxing.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: [WIP] Work in progress

#207 Impl isna
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/hiframes/series_kernels.py
  hpat/str_arr_ext.py
  hpat/tests/test_series.py
Labels: question

#243 Series tests fix 1
  hpat/tests/test_series.py
Labels: bug

#228 Refactor Series.median() in a new style via np.median
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: [WIP] Work in progress

#192 Implement series.cumsum() in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#249 PyArrow porting 0.14.1 -> 0.15.0
  README.rst
  buildscripts/hpat-conda-recipe/meta.yaml
  buildscripts/parquet-reader-conda-recipe/meta.yaml
  parquet_reader/hpat_parquet_reader.cpp
Labels: [WIP] Work in progress, enhancement

#223 Implement Series.head()
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#222 Implement Series.std() in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Depends on other PR

#220 Implement series.var() in new style
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Waiting on author

#247 Implement notna
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/hiframes_typed.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#260 Implement Series.isnull (alias isna)
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: Ready for Review

#251 Refactor Series.fillna() in a new style and add more tests
  hpat/datatypes/hpat_pandas_series_functions.py
  hpat/hiframes/pd_series_ext.py
  hpat/tests/test_series.py
Labels: FullyApproved
