Repository IntelPython/sdc, pull requests merged in 2019-12, with the labels that each got.

#350 Move TestCase to sdc/tests/test_base.py
  sdc/tests/test_base.py
  sdc/tests/test_basic.py
  sdc/tests/test_d4p.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_date.py
  sdc/tests/test_groupby.py
  sdc/tests/test_hiframes.py
  sdc/tests/test_hpat_jit.py
  sdc/tests/test_io.py
  sdc/tests/test_join.py
  sdc/tests/test_ml.py
  sdc/tests/test_rolling.py
  sdc/tests/test_series.py
  sdc/tests/test_strings.py
  sdc/tests/test_utils.py
Labels: Ready for Review

#351 Replace sdc.jit with self.jit for using numba.jit for new pipeline
  sdc/tests/test_basic.py
  sdc/tests/test_d4p.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_date.py
  sdc/tests/test_groupby.py
  sdc/tests/test_hiframes.py
  sdc/tests/test_hpat_jit.py
  sdc/tests/test_io.py
  sdc/tests/test_join.py
  sdc/tests/test_ml.py
  sdc/tests/test_rolling.py
  sdc/tests/test_series.py
  sdc/tests/test_strings.py
Labels: Ready for Review

#339 Fix series perf tests in new style
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready to merge

#321 Add series.str.len() in new style
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Waiting on CI

#348 fix Series.cov
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#359 Skip hanging tests in test_basic
  sdc/tests/test_basic.py
  sdc/tests/test_hiframes.py
Labels: Ready to merge

#353 Fix corr1
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready for Review

#352 extended test mode for benchmarks
  buildscripts/test.py
Labels: Waiting on author

#357 Use numpy 1.17; remove builds for numba master
  .travis.yml
  azure-pipelines.yml
Labels: Ready for Review, Ready to merge

#344 Merge numba master
  .travis.yml
  azure-pipelines.yml
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  sdc/distributed.py
  sdc/hiframes/aggregate.py
  sdc/hiframes/dataframe_pass.py
  sdc/hiframes/filter.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/join.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_series_ext.py
  sdc/io/csv_ext.py
  sdc/tests/test_basic.py
  sdc/tests/test_d4p.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_date.py
  sdc/tests/test_groupby.py
  sdc/tests/test_hiframes.py
  sdc/tests/test_hpat_jit.py
  sdc/tests/test_io.py
  sdc/tests/test_join.py
  sdc/tests/test_ml.py
  sdc/tests/test_rolling.py
  sdc/tests/test_series.py
  sdc/tests/test_strings.py
  sdc/tests/test_utils.py
  setup.py
Labels: Ready to merge

#365 Performance tests on series methods in workload
  sdc/tests/test_utils.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#373 Series rename new pipeline
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Ready for Review, Waiting on CI

#381 Revert "Impl operator setitem"
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: FullyApproved

#360 Overload Series(StringArraySplitView).str.len()
  sdc/datatypes/hpat_pandas_stringmethods_types.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/pd_series_ext.py
  sdc/hiframes/split_impl.py
  sdc/tests/test_hiframes.py
Labels: Ready to merge

#380 Implement Series.str.isupper() in new style
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/hiframes/split_impl.py
  sdc/tests/test_series.py
Labels: Ready for Review

#379 added 'xlrd' for benchmark tests conda env
  buildscripts/test.py
Labels: Ready to merge, Waiting on CI

#382 Implement Series.str.find()
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Waiting on CI

#384 Implement Series.str.endswith()
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Ready to merge

#383 Implement Series.str.startswith()
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Ready to merge

#385 Implement Series.str.center()
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Ready for Review

#396 Revert unnecessary code modifications
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Waiting on CI

#378 Remove old performance tests as unused ones
  tests_perf/README.md
  tests_perf/__init__.py
  tests_perf/asv.conf.json
  tests_perf/asv_hpat_plugin.py
  tests_perf/asvgen.py
  tests_perf/benchmark.py
  tests_perf/build_hpat.py
  tests_perf/runner.py
  tests_perf/templates/asvgen.html
  tests_perf/tests/__init__.py
  tests_perf/tests/algorithms.py
  tests_perf/tests/common.py
  tests_perf/tests/data_generator.py
  tests_perf/tests/io/__init__.py
  tests_perf/tests/io/csv.py
  tests_perf/tests/series.py
  tests_perf/tests/unicode_strings.py
Labels: Ready to merge

#305 Add support for Series.operator.add in a new-style
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Waiting on CI

#392 Implement Series.str.ljust()/rjust()
  examples/series_str_ljust.py
  examples/series_str_rjust.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: FullyApproved

#397 Implement Series.str.zfill()
  examples/series_str_zfill.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Coverage decreased, FullyApproved

#349 Make PyArrow cpu_count to correspond NUMBA_NUM_THREADS
  sdc/io/csv_ext.py
  sdc/tests/tests_perf/gen_csv.py
  sdc/tests/tests_perf/test_perf_read_csv.py
Labels: Ready to merge

#407 Merge numba-master and update numba to recent version with overloads inlining
  .travis.yml
  azure-pipelines.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/build.py
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  buildscripts/test.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/distributed.py
  sdc/hiframes/aggregate.py
  sdc/hiframes/filter.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/join.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_series_ext.py
  sdc/io/csv_ext.py
  sdc/io/np_io.py
  sdc/set_ext.py
  sdc/tests/test_basic.py
  sdc/tests/test_d4p.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_date.py
  sdc/tests/test_groupby.py
  sdc/tests/test_ml.py
  sdc/utils.py
  setup.py
Labels: Ready to merge

#415 Change llvmlite version to 0.31.0dev0 py*_0 for Numba build
  buildscripts/numba-conda-recipe/recipe/meta.yaml
Labels: Waiting on CI

#416 Add SDC examples execution in public CI
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/test.py
  examples/series_at.py
  examples/series_getitem.py
  examples/series_nlargest.py
  examples/series_nsmallest.py
Labels: Waiting on CI, [WIP] Work in progress

#417 Overload series.rolling.max()
  examples/series/rolling/series_rolling_max.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#402 Provide documentations for series string methods
  examples/series/str/series_str_center.py
  examples/series/str/series_str_endswith.py
  examples/series/str/series_str_find.py
  examples/series/str/series_str_isupper.py
  examples/series/str/series_str_len.py
  examples/series/str/series_str_ljust.py
  examples/series/str/series_str_rjust.py
  examples/series/str/series_str_startswith.py
  examples/series/str/series_str_zfill.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Ready for Review

#404 Update Series.value_counts() to handle dropna argument and handle NaN/None values
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready to merge

#403 Provide documentation for Series methods
  examples/series/series_abs.py
  examples/series/series_add.py
  examples/series/series_count.py
  examples/series/series_div.py
  examples/series/series_max.py
  examples/series/series_mul.py
  examples/series/series_quantile.py
  examples/series/series_truediv.py
  examples/series/series_unique.py
  examples/series/series_value_counts.py
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Coverage decreased, Ready for Review

#419 Overload Series.rolling.count()
  examples/series/rolling/series_rolling_count.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready to merge

#432 Fix windows issue with conda build
  buildscripts/build.py
Labels: Ready for Review, Waiting on CI

#421 Overload series.rolling.sum()
  examples/series/rolling/series_rolling_sum.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready to merge, Waiting on CI

#423 Overload series.rolling.mean()
  examples/series/rolling/series_rolling_mean.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready to merge, Waiting on CI

#424 Overload series.rolling.median()
  examples/series/rolling/series_rolling_median.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready to merge, Waiting on CI

#425 Overload series.rolling.var()
  examples/series/rolling/series_rolling_var.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready to merge, Waiting on CI

#426 Overload series.rolling.std()
  examples/series/rolling/series_rolling_std.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready for Review, Waiting on CI

#428 Overload series.rolling.corr()
  examples/series/rolling/series_rolling_corr.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready for Review, Waiting on CI

#430 Fix lnk to docs in README.rst
  README.rst
Labels: Ready for Review, Waiting on CI

#431 Fix readme whitespace
  README.rst
Labels: Ready for Review, Waiting on CI

#429 Add SDC_TEST_EXPECTED_FAILURE
  sdc/config.py
  sdc/tests/test_utils.py
Labels: Coverage decreased, Ready for Review, Waiting on CI

#448 Move SDC master to Numba master
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  sdc/str_arr_ext.py
  sdc/tests/test_date.py
  sdc/tests/test_series.py
Labels: Ready for Review

#447 Update examples execution
  buildscripts/test.py
Labels: Ready for Review, Waiting on CI

#441 Add UNEXPECTED SUCCEESS for examples CI
  buildscripts/test.py
Labels: Ready to merge, Waiting on CI

#440 Support for empty strings in read_csv()
  sdc/hiframes/hiframes_untyped.py
  sdc/io/csv_ext.py
  sdc/tests/gen_test_data.py
  sdc/tests/test_hpat_jit.py
  sdc/tests/test_io.py
Labels: Coverage decreased, Ready for Review

#410 Extends setup.py with build_doc command
  docs/source/buildscripts/sdc_build_doc.py
  docs/source/conf.py
  setup.py
Labels: Documentation

#389 Fix series index and names issues pt.1
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
  sdc/tests/test_utils.py
Labels: Coverage decreased, Ready for Review, Waiting on CI

#433 Overload series.rolling.cov()
  examples/series/rolling/series_rolling_cov.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready to merge

#434 Overload series.rolling.quantile()
  examples/series/rolling/series_rolling_quantile.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready to merge

#412 Implement pandas.read_csv() in numba.jit
  buildscripts/test.py
  sdc/datatypes/hpat_pandas_functions.py
  sdc/hiframes/hiframes_untyped.py
  sdc/io/csv_ext.py
  sdc/tests/test_io.py
Labels: Ready for Review

#413 Refactor arithmetic and comparison series binops to a new-style
  buildscripts/autogen_sources.py
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_autogenerated.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/sdc_function_templates.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready to merge

#394 Add setitem
  examples/series_setitem_int.py
  examples/series_setitem_series.py
  examples/series_setitem_slice.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#366 add reduce
  sdc/__init__.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_types.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased, Ready for Review

#452 Add isspace
  examples/series/str/series_str_isspace.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#458 Add isalpha
  examples/series/str/series_str_isalpha.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased

#456 impl str.islower
  examples/series/str/series_str_islower.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#454 Add isalnum
  examples/series/str/series_str_isalnum.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased

#362 Refactor Series.describe to a new-style
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#361 Implement getitem
  examples/series_at/series_at_multiple_result.py
  examples/series_at/series_at_single_result.py
  examples/series_getitem/series_getitem_bool_array.py
  examples/series_getitem/series_getitem_scalar_multiple_result.py
  examples/series_getitem/series_getitem_scalar_single_result.py
  examples/series_getitem/series_getitem_series.py
  examples/series_getitem/series_getitem_slice.py
  examples/series_iat.py
  examples/series_iloc/series_iloc_slice.py
  examples/series_iloc/series_iloc_value.py
  examples/series_loc/series_loc_multiple_result.py
  examples/series_loc/series_loc_single_result.py
  examples/series_loc/series_loc_slice.py
  sdc/datatypes/hpat_pandas_getitem_types.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_hiframes.py
  sdc/tests/test_series.py
  sdc/tests/test_strings.py
Labels: Ready for Review, Waiting on CI

#345 Add functions for dataframe: median, mean, min, max, sum
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased
