Repository IntelPython/sdc, pull requests merged in 2019-08, with the labels that each got.

#103 HPAT Build: Code style check for C and Python sources
  .clang-format
  setup.py
Labels: enhancement

#106 Code style change part 1
  examples/accel_example.py
  examples/d4p_kmeans.py
  examples/d4p_linreg.py
  examples/hiframes_concat.py
  examples/hiframes_cumsum.py
  examples/hiframes_filter.py
  examples/hiframes_merge.py
  examples/hiframes_pivot.py
  examples/hiframes_rolling.py
  examples/hiframes_shift.py
  examples/hiframes_sort.py
  examples/intraday_mean.py
  examples/intraday_mean_rand.py
  examples/k-means.py
  examples/kernel_density_estimation.py
  examples/kernel_density_estimation_pq.py
  examples/kernel_density_estimation_pq_hdfs.py
  examples/linear_regression.py
  examples/logistic_regression.py
  examples/logistic_regression_rand.py
  examples/ml_mnb.py
  examples/ml_svc.py
  examples/pi.py
  examples/ros_example1.py
  setup.py
  tutorial/intraday_mean.py
Labels: enhancement

#99 Fix for Pandas merge overload wrong handling of string literals
  hpat/hiframes/pd_dataframe_ext.py
  hpat/tests/test_join.py
Labels: FullyApproved

#108 Add more check in style configuration
  .clang-format
Labels: enhancement

#92 Fix boost runtime issue on Ubuntu16.04 with gcc 5.4
  hpat/_meminfo.h
  hpat/_str_decode.cpp
  hpat/_str_ext.cpp
  hpat/io/_csv.cpp
  hpat/stringlib/codecs.h
  parquet_reader/hpat_parquet_reader.cpp
Labels: bug

#100 Unskipping unit tests from test_basic.py that currently pass
  hpat/tests/test_basic.py
  hpat/tests/test_series.py
Labels: [WIP} Work in progress

#124 Add timer to non-mpi transport
  hpat/config.py
  hpat/transport/hpat_transport_single_process.cpp
Labels: bug
