Repository IntelPython/sdc, pull requests merged in 2020-01, with the labels that each got.

#444 Overload series.rolling.skew()
  examples/series/rolling/series_rolling_skew.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#436 Overload series.rolling.apply()
  examples/series/rolling/series_rolling_apply.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Coverage decreased, Ready for Review

#446 Overload series.rolling.kurt()
  examples/series/rolling/series_rolling_kurt.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#468 Overload DataFrame.rolling() + DataFrame.rolling.min()
  examples/dataframe/rolling/dataframe_rolling_min.py
  sdc/__init__.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_types.py
  sdc/datatypes/hpat_pandas_rolling_types.py
  sdc/tests/test_rolling.py
Labels: Ready to merge

#401 DataFrame.append
  examples/dataframe/dataframe_append.py
  sdc/__init__.py
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased, Ready for Review

#467 Df pct change
  examples/dataframe_pct_change.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased

#470 Refactor series.rolling
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_types.py
Labels: Ready for Review

#473 update test.py
  buildscripts/test.py
Labels: Ready to merge, Waiting on CI

#442 DataFrame.drop
  examples/dataframe/dataframe_drop.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased, Ready for Review

#443 Add documentation and examples on Series methods
  examples/series/series_argsort.py
  examples/series/series_eq.py
  examples/series/series_ge.py
  examples/series/series_gt.py
  examples/series/series_head.py
  examples/series/series_idxmax.py
  examples/series/series_idxmin.py
  examples/series/series_isna.py
  examples/series/series_isnull.py
  examples/series/series_le.py
  examples/series/series_lt.py
  examples/series/series_min.py
  examples/series/series_ne.py
  examples/series/series_notna.py
  examples/series/series_pow.py
  examples/series/series_sort_values.py
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#500 add perf tests
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#499 Add first benchmark test for DataFrame methods
  sdc/tests/tests_perf/__init__.py
  sdc/tests/tests_perf/test_perf_df.py
Labels: Ready for Review

#471 Loc with slice
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#422 Implement series.apply()
  examples/series/series_apply.py
  examples/series/series_apply_lambda.py
  examples/series/series_apply_log.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/pandas_series_functions/__init__.py
  sdc/datatypes/pandas_series_functions/apply.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
  sdc/tests/test_series_apply.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#450 Redesign Series.sort_values new-style impl
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/pd_series_ext.py
  sdc/str_arr_ext.py
  sdc/tests/test_series.py
Labels: Ready for Review

#517 Add perf.test on df.rolling.min()
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/__init__.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#524 Removed outdated files
  buildscripts/sdc_pi_example.py
  docker/Dockerfile
  docker/build_instance/Dockerfile
  docker/docker-compose.yml
  docker/docker_anaconda_4.4/Dockerfile
  docker/docker_anaconda_4.4/docker-compose.yml
  docs/demos/plotting.py
  docs/demos/sdc_demo.ipynb
  examples/old_examples/Basic_DataFrame.py
  examples/old_examples/accel_example.py
  examples/old_examples/d4p_kmeans.py
  examples/old_examples/d4p_linreg.py
  examples/old_examples/hiframes_concat.py
  examples/old_examples/hiframes_cumsum.py
  examples/old_examples/hiframes_filter.py
  examples/old_examples/hiframes_merge.py
  examples/old_examples/hiframes_pivot.py
  examples/old_examples/hiframes_rolling.py
  examples/old_examples/hiframes_shift.py
  examples/old_examples/hiframes_sort.py
  examples/old_examples/intraday_mean_rand.py
  examples/old_examples/kernel_density_estimation_pq.py
  examples/old_examples/kernel_density_estimation_pq_hdfs.py
  examples/old_examples/logistic_regression_rand.py
  examples/old_examples/pi.py
  examples/old_examples/ros_example1.py
  examples/old_examples/series_basic.py
  tutorial/README.md
  tutorial/cycling_dataset.csv
  tutorial/cycling_dataset.pq
  tutorial/cycling_test_dataset.pq
  tutorial/cycling_train_dataset.pq
  tutorial/daal4py_data_science.ipynb
  tutorial/hpat.ipynb
  tutorial/img/data-parallel.jpg
  tutorial/img/file-read.jpg
  tutorial/img/groupby.jpg
  tutorial/img/reduction.jpg
  tutorial/img/rolling.jpg
Labels: Ready for Review

#521 Removed mpi dependency
  buildscripts/sdc-conda-recipe/meta.yaml
  buildscripts/sdc-conda-recipe/run_test.bat
  buildscripts/sdc-conda-recipe/run_test.sh
  requirements.txt
  sdc/decorators.py
  sdc/distributed_api.py
  sdc/distributed_lower.py
  sdc/hiframes/api.py
  sdc/hiframes/join.py
  sdc/io/csv_ext.py
  sdc/io/np_io.py
  sdc/tests/gen_test_data.py
  sdc/tests/test_base.py
  sdc/tests/test_basic.py
  sdc/tests/test_d4p.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_date.py
  sdc/tests/test_groupby.py
  sdc/tests/test_hiframes.py
  sdc/tests/test_hpat_jit.py
  sdc/tests/test_io.py
  sdc/tests/test_join.py
  sdc/tests/test_ml.py
  sdc/tests/test_rolling.py
  sdc/tests/test_series.py
  sdc/tests/test_series_apply.py
  sdc/tests/test_strings.py
  sdc/tests/test_utils.py
  sdc/transport/hpat_transport_mpi.cpp
  setup.py
Labels: Ready for Review

#520 Suppress SAT-2330 issue
  sdc/tests/test_series.py
Labels: Waiting on CI

#498 Loc array
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Coverage decreased, Ready for Review

#472 Overload df.rolling.apply()
  examples/dataframe/rolling/dataframe_rolling_apply.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#474 Overload df.rolling.count()
  examples/dataframe/rolling/dataframe_rolling_count.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#476 Overload df.rolling.max()
  examples/dataframe/rolling/dataframe_rolling_max.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#475 Overload df.rolling.kurt()
  examples/dataframe/rolling/dataframe_rolling_kurt.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#533 Disabling parallel execution for rolling and other
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_series.py
  sdc/utils.py
Labels: Ready to merge

#477 Overload df.rolling.mean()
  examples/dataframe/rolling/dataframe_rolling_mean.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#494 Overload df.rolling.corr()
  examples/dataframe/rolling/dataframe_rolling_corr.py
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Coverage decreased, Ready for Review

#478 Overload df.rolling.median()
  examples/dataframe/rolling/dataframe_rolling_median.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#512 Docs for getitem/loc/iloc/at/iat
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#519 Use prange in apply
  sdc/datatypes/pandas_series_functions/apply.py
  sdc/tests/test_series_apply.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#529 Implement Series.map()
  examples/series/series_map.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/pandas_series_functions/map.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
  sdc/tests/test_series_map.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Waiting on CI

#479 Overload df.rolling.skew()
  examples/dataframe/rolling/dataframe_rolling_skew.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#527 Add docs for 13 series func
  examples/series/series_T.py
  examples/series/series_astype.py
  examples/series/series_index.py
  examples/series/series_isin.py
  examples/series/series_ndim.py
  examples/series/series_nlargest.py
  examples/series/series_nsmallest.py
  examples/series/series_shape.py
  examples/series/series_shift.py
  examples/series/series_size.py
  examples/series/series_std.py
  examples/series/series_values.py
  examples/series/series_var.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready for Review

#531 Cleaning up in test_series.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_rolling.py
  sdc/tests/test_series.py
Labels: Ready for Review

#522 generic for perf_tests
  sdc/tests/tests_perf/generator.py
  sdc/tests/tests_perf/test_perf_base.py
  sdc/tests/tests_perf/test_perf_df.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
  sdc/tests/tests_perf/test_perf_series.py
  sdc/tests/tests_perf/test_perf_series_str.py
Labels: Coverage decreased

#544 Pandas 0.25
  .travis.yml
  buildscripts/build.py
  buildscripts/sdc-conda-recipe/meta.yaml
  buildscripts/test.py
Labels: Ready for Review, Waiting on CI

#480 Overload df.rolling.sum()
  examples/dataframe/dataframe_rolling_sum.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#481 Overload df.rolling.quantile()
  examples/dataframe/rolling/dataframe_rolling_quantile.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#497 Adding support for StringArrays comparison operators
  buildscripts/autogen_sources.py
  docs/source/buildscripts/sdc_info.py
  docs/source/buildscripts/sdc_object_utils.py
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_pass.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_rolling_types.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/datatypes/hpat_pandas_seriesgroupby_functions.py
  sdc/datatypes/hpat_pandas_seriesgroupby_types.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/datatypes/hpat_pandas_stringmethods_types.py
  sdc/datatypes/pandas_series_functions/apply.py
  sdc/datatypes/pandas_series_functions/map.py
  sdc/dict_ext.py
  sdc/distributed.py
  sdc/distributed_analysis.py
  sdc/distributed_api.py
  sdc/distributed_lower.py
  sdc/hiframes/aggregate.py
  sdc/hiframes/api.py
  sdc/hiframes/dataframe_pass.py
  sdc/hiframes/filter.py
  sdc/hiframes/hiframes_typed.py
  sdc/hiframes/hiframes_untyped.py
  sdc/hiframes/join.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_groupby_ext.py
  sdc/hiframes/pd_series_ext.py
  sdc/hiframes/pd_timestamp_ext.py
  sdc/hiframes/rolling.py
  sdc/hiframes/sort.py
  sdc/io/csv_ext.py
  sdc/io/parquet_pio.py
  sdc/sdc_autogenerated.py
  sdc/sdc_function_templates.py
  sdc/set_ext.py
  sdc/shuffle_utils.py
  sdc/str_arr_ext.py
  sdc/str_arr_type.py
  sdc/str_ext.py
  sdc/tests/test_series.py
  sdc/timsort.py
  sdc/utilities/__init__.py
  sdc/utilities/sdc_typing_utils.py
  sdc/utilities/utils.py
Labels: Coverage decreased, Ready for Review
