Repository IntelPython/sdc, pull requests merged in 2020-02, with the labels that each got.

#482 Overload df.rolling.std()
  examples/dataframe/rolling/dataframe_rolling_std.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#483 Overload df.rolling.var()
  examples/dataframe/rolling/dataframe_rolling_var.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#560 Update Travis config
  .coveralls.yml
  .travis.yml
  README.rst
Labels: Ready for Review, Waiting on CI

#559 Overload df.getitem for str idx
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_utils.py
Labels: Ready for Review

#564 Update sdc recipe
  buildscripts/sdc-conda-recipe/meta.yaml
  sdc/tests/test_series.py
Labels: Ready for Review, Waiting on CI

#558 Add test on index for series.rolling.corr
  sdc/tests/test_rolling.py
Labels: Ready for Review

#561 Remove dependency from boost
  sdc/__init__.py
  sdc/_dict_ext.cpp
  sdc/_str_ext.cpp
  sdc/dict_ext.py
  sdc/io/_csv.cpp
  sdc/io/_csv.h
  sdc/io/_io.cpp
  sdc/io/csv_ext.py
  sdc/str_ext.py
  sdc/tests/test_strings.py
  setup.py
Labels: Ready for Review

#551 Series str methods
  examples/series/str/series_str_capitalize.py
  examples/series/str/series_str_casefold.py
  examples/series/str/series_str_swapcase.py
  examples/series/str/series_str_title.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/hiframes/pd_series_ext.py
  sdc/tests/test_series.py
  sdc/tests/tests_perf/test_perf_series_str.py
Labels: Waiting on CI

#566 Overload df.getitem with slice idx
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_utils.py
Labels: Ready for Review

#573 Overload df.getitem with idx of tuple
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#536 Refactoring Series.setitem to support pd.Series as value and index based assignment
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
  sdc/tests/test_utils.py
Labels: Ready to merge

#583 Overload df.getitem with boolean series idx
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
  sdc/utilities/sdc_typing_utils.py
Labels: Ready for Review

#526 DataFrame.values impl
  examples/dataframe/dataframe_values.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Coverage decreased, Ready for Review

#547 Overload df.rolling.cov, add perf.test
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready for Review

#601 Implement initial version of rewrite for df.getitem as attr
  sdc/__init__.py
  sdc/rewrites/dataframe_getitem_attribute.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#596 Add Boolean handling to Series.value_counts
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready for Review

#612 Move prange utils in separate PR
  sdc/utilities/prange_utils.py
Labels: Ready for Review

#605 Remove test that causes segfault
  sdc/tests/test_strings.py
Labels: Ready for Review

#607 Unskip 9 tests on df.getitem
  sdc/rewrites/dataframe_getitem_attribute.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#582 Fix for DataFrame str column created as List of Optional values
  sdc/hiframes/api.py
  sdc/str_arr_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_series.py
  sdc/tests/test_utils.py
Labels: Ready for Review

#562 Update SDC build instruction in Readme.rst
  README.rst
Labels: Ready for Review, Waiting on CI

#590 Initial support of DataFrame.GroupBy by single literal column
  sdc/__init__.py
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/datatypes/hpat_pandas_groupby_types.py
  sdc/hiframes/api.py
  sdc/hiframes/pd_groupby_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_groupby.py
  sdc/utilities/sdc_typing_utils.py
Labels: Ready for Review

#587 Overload df.getitem with bool array idx
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#622 Adding initial support for DataFrameGroupBy.getitem
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/datatypes/hpat_pandas_groupby_types.py
  sdc/tests/test_groupby.py
Labels: Ready for Review

#608 Optimize series.rolling.sum()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
  sdc/utilities/prange_utils.py
Labels: Ready for Review

#627 Add index to df.drop()
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review, Waiting on CI

#611 Optimize dseries.rolling.mean()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#629 GroupBy.getitem for single column case aligned with pandas
  examples/series/series_groupby.py
  sdc/__init__.py
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/datatypes/hpat_pandas_groupby_types.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_seriesgroupby_functions.py
  sdc/datatypes/hpat_pandas_seriesgroupby_types.py
  sdc/tests/test_groupby.py
  sdc/tests/test_series.py
Labels: Ready for Review

#633 Update readme
  README.rst
Labels: Ready for Review, Waiting on CI

#613 Optimize series.rolling.min()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#634 Optimize series.rolling.kurt()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#642 Optimize series.rolling.skew()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#647 Fix multithreading issue for series.rolling
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
Labels: Ready to merge

#643 Add script for documentation build / publish; start build/test refactor
  azure-pipelines.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/build.py
  buildscripts/build_doc.py
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  buildscripts/sdc-conda-recipe/conda_build_config.yaml
  buildscripts/sdc-conda-recipe/meta.yaml
  buildscripts/test.py
  buildscripts/utilities.py
  docs/source/conf.py
Labels: Ready for Review, Waiting on CI

#654 Fix potential issue when window == 0 in rolling
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
Labels: Ready for Review
