Repository IntelPython/sdc, pull requests merged in 2020-05, with the labels that each got.

#818 change README
  README.rst
  docs/README.rst
Labels: Ready for Review

#830 Enable CI for feature/groupby_optimization
  .travis.yml
  azure-pipelines.yml
Labels: Ready for Review

#832 Improve boxing
  sdc/hiframes/boxing.py
Labels: Ready for Review

#837 Specify sdc version from channel for examples testing
  buildscripts/run_examples.py
  buildscripts/utilities.py
Labels: Waiting on CI, [WIP] Work in progress

#845 Re-implement df.getitem based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_dataframe_type.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#846 Re-implement df.values based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#847 Re-implement df.pct_change based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#848 Re-implement df.drop based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#851 Move conda recipe to sdc/conda-recipe folder
  README.rst
  buildscripts/utilities.py
  conda-recipe/bld.bat
  conda-recipe/build.sh
  conda-recipe/conda_build_config.yaml
  conda-recipe/meta.yaml
  conda-recipe/run_test.bat
  conda-recipe/run_test.sh
Labels: Ready to merge

#857 Re-implement df.append based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready to merge

#849 Re-implement df.reset_index based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#850 Re-implement df._set_column based on new strcture
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#852 Re-implement df.rolling methods based on new structure
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#853 Re-implement df.index based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#854 Re-implement df.copy based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#856 Re-implement df.isna based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#858 Re-implement df.at/iat/loc/iloc based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#855 Re-implement df.head based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready to merge

#859 Re-implement df.groupby methods based on new structure
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/tests/test_groupby.py
Labels: Ready for Review

#603 Parallel isin
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#861 Re-implement dataframe boxing based on new structure
  sdc/hiframes/boxing.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_groupby.py
  sdc/tests/test_io.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#860 Re-implement DataFrame unboxing
  sdc/hiframes/boxing.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_groupby.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#865 Re-implement df structure: Fix rolling
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
Labels: Ready for Review

#866 Undecorate tests on reading CSV
  sdc/tests/test_io.py
Labels: Ready for Review

#867 Re-implement df structure: enable rolling tests that pass
  sdc/tests/test_rolling.py
Labels: Ready for Review

#868 Re-implement df structure: refactor len
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_groupby.py
  sdc/tests/test_rolling.py
  sdc/tests/test_utils.py
Labels: Ready for Review

#870 Merge refactored DataFrame to master
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/hiframes/boxing.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/hiframes/pd_dataframe_type.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_groupby.py
  sdc/tests/test_rolling.py
Labels: Ready for Review

#871 Undecorate test_min_dataframe_default
  sdc/tests/test_dataframe.py
Labels: Ready for Review
