Repository IntelPython/sdc, pull requests merged in 2020-03, with the labels that each got.

#646 Optimize series.rolling.var()/std()
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#614 Optimize rolling max
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
Labels: Ready for Review

#626 Optimize series rolling count
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#637 Adding performance tests for DataFrame.groupby
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/tests/tests_perf/__init__.py
  sdc/tests/tests_perf/test_perf_df_groupby.py
Labels: Ready for Review

#632 Adding some perf tests on Series.getitem
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#645 FIX df operations fail when spaces in column names
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#668 Update SDC wheels build
  requirements.txt
  sdc/io/parquet_pio.py
  setup.py
Labels: Ready for Review, Waiting on CI

#649 Optimize series.rolling.corr()
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#661 Doc for getitem
  docs/source/api_ref/pandas.Series.getitem.rst
Labels: Ready for Review

#664 doc for Series.setitem
  docs/source/api_ref/pandas.Series.setitem.rst
Labels: Ready for Review

#666 Optimize rolling.cov
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/tests/test_rolling.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready for Review

#675 Remove opencv dependency
  sdc/_cv.cpp
  sdc/config.py
  setup.py
Labels: Ready for Review, Waiting on CI

#676 Update examples execution
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/run_examples.py
  buildscripts/utilities.py
Labels: Ready for Review

#672 Implement private df method _set_column which currently sets non-existing column to the df
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#682 Implement private df method _set_column which sets existing column to the df
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
  sdc/utilities/sdc_typing_utils.py
Labels: Ready for Review

#673 Changing perf tests data generation and adding perf tests
  sdc/tests/tests_perf/data_generator.py
  sdc/tests/tests_perf/generator.py
  sdc/tests/tests_perf/test_perf_df.py
  sdc/tests/tests_perf/test_perf_numpy.py
  sdc/tests/tests_perf/test_perf_series.py
  sdc/tests/tests_perf/test_perf_series_operators.py
  sdc/tests/tests_perf/test_perf_series_rolling.py
  sdc/tests/tests_perf/test_perf_series_str.py
  sdc/tests/tests_perf/test_perf_utils.py
Labels: Ready for Review

#679 Scale getitem by Boolean mask (array or Series) for Series and DFs
  sdc/datatypes/common_functions.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/functions/numpy_like.py
  sdc/tests/test_dataframe.py
  sdc/tests/test_series.py
Labels: Ready for Review

#706 Make config_use_parallel_overloads True by default
  sdc/config.py
Labels: Ready for Review

#662 Df.iat impl
  examples/dataframe/dataframe_iat.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_getitem_types.py
  sdc/hiframes/pd_dataframe_ext.py
  sdc/tests/test_dataframe.py
Labels: Waiting on CI

#658 Df.copy impl
  examples/dataframe/dataframe_copy.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_dataframe.py
  sdc/tests/tests_perf/test_perf_df.py
Labels: Ready to merge

#665 Doc for df getitem
  docs/source/_templates/_api_ref.pandas.dataframe_templ.rst
  docs/source/buildscripts/apiref_generator.py
  docs/source/buildscripts/sdc_object_utils.py
  examples/dataframe/df_getitem/df_getitem.py
  examples/dataframe/df_getitem/df_getitem_array.py
  examples/dataframe/df_getitem/df_getitem_attr.py
  examples/dataframe/df_getitem/df_getitem_series.py
  examples/dataframe/df_getitem/df_getitem_slice.py
  examples/dataframe/df_getitem/df_getitem_tuple.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#719 Fix docstrings for series.str methods
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Ready for Review

#708 Doc for df getitem
  docs/source/_templates/_api_ref.pandas.dataframe_templ.rst
  docs/source/buildscripts/apiref_generator.py
  docs/source/buildscripts/sdc_object_utils.py
  examples/dataframe/getitem/df_getitem.py
  examples/dataframe/getitem/df_getitem_array.py
  examples/dataframe/getitem/df_getitem_attr.py
  examples/dataframe/getitem/df_getitem_series.py
  examples/dataframe/getitem/df_getitem_slice.py
  examples/dataframe/getitem/df_getitem_tuple.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#701 correct doc for Series.str.strip, lstrip, rstrip
  examples/series/str/series_str_lstrip.py
  examples/series/str/series_str_rstrip.py
  examples/series/str/series_str_strip.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#696 correct doc for Series.cumsum
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#729 Fix docstring for series.take()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#720 Fix docstring for Series.values
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#728 Docs for Series.map()
  sdc/datatypes/pandas_series_functions/map.py
Labels: Ready to merge

#731 Docs for Series.prod()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#724 Docs Series.apply()
  sdc/datatypes/pandas_series_functions/apply.py
Labels: Ready to merge

#726 Docs for pandas.read_csv()
  docs/source/_templates/_api_ref.pandas.io_templ.rst
  docs/source/apireference.rst
  docs/source/buildscripts/apiref_generator.py
  sdc/datatypes/hpat_pandas_functions.py
Labels: Ready to merge

#727 Use NUMBA_DISABLE_PERFORMANCE_WARNINGS to disable example's warnings
  buildscripts/build_doc.py
Labels: Ready to merge

#725 Docs series copy
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#736 Fix docstring for Series.truediv()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#734 Fix docstring for Series.max()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#735 Fix docstring for Series.mul()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#697 correct doc for Series.idxmax
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#698 correct doc for Series.idxmin
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#715 Fix docstring for Series.count()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#737 Fix docstring for Series.value_counts()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#732 Docs for Series.sum()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#695 correct doc for df.append
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready for Review

#723 Docs for pandas.Series()
  docs/source/buildscripts/sdc_object_utils.py
  sdc/hiframes/pd_series_ext.py
  sdc/rewrites/dataframe_constructor.py
Labels: Ready for Review

#730 Docs for Series.mean()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready for Review

#739 strip, lstrip, rstrip work with NaN
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready for Review

#733 Fix docstrings for rolling methods
  examples/dataframe/rolling/dataframe_rolling_cov.py
  examples/dataframe/rolling/dataframe_rolling_sum.py
  sdc/datatypes/hpat_pandas_rolling_types.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
Labels: Ready for Review

#657 Perf test for series rolling max
  sdc/tests/tests_perf/test_perf_series_rolling.py
Labels: Ready to merge

#640 Series str rjust
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#638 Series str center
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#713 Fix docstring for series.std/var()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#711 Fix docstring for series.shift()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#742 correct doc for Series.setitem
  docs/source/_templates/_api_ref.pandas.series_templ.rst
  docs/source/api_ref/pandas.Series.setitem.rst
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#718 Doc for Series.sort_values
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#716 Doc Series.loc/iloc
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#712 Improve docstring for Series.add()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#710 Fix docstring for series.nlargest/nsmallest()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#702 correct doc for Series.str.upper
  examples/series/str/series_str_upper.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#690 correct doc for DF.pct_change
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#721 Fix docstring for Series.div()
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#747 Fix Pandas->SDC docs formatting.
  docs/source/buildscripts/apiref_generator.py
Labels: Ready to merge

#741 correct doc for Series.getitem
  docs/source/_templates/_api_ref.pandas.series_templ.rst
  docs/source/api_ref/pandas.Series.getitem.rst
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#740 Add docstring for df.setitem
  docs/source/_templates/_api_ref.pandas.dataframe_templ.rst
  examples/dataframe/setitem/df_set_existing_column.py
  examples/dataframe/setitem/df_set_new_column.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#717 Doc for Series.min
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#714 Doc for Series.argsort
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge, Waiting on CI

#709 Improve docstring for df.drop()
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#699 correct doc for Series.quantile
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge, Waiting on CI

#694 correct doc for DF.var
  examples/dataframe/dataframe_var.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#693 correct doc for DF.sum
  examples/dataframe/dataframe_sum.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#689 correct doc for DF.min
  examples/dataframe/dataframe_min.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#686 Correct doc for df max
  examples/dataframe/dataframe_max.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#683 correct doc for DF.count
  examples/dataframe/dataframe_count.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge, Waiting on CI

#745 Fixing a bug with wrong order of values in groupby when sort=True
  sdc/datatypes/hpat_pandas_groupby_functions.py
  sdc/tests/test_groupby.py
  sdc/tests/test_series.py
Labels: Ready to merge

#744 Initial attempt to parallelize groupby
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_groupby_functions.py
Labels: Ready to merge

#705 Df.append() add index handling
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/tests/test_dataframe.py
Labels: Ready for Review

#748 Disable perf test getitem_idx_int_series
  sdc/tests/tests_perf/test_perf_series.py
Labels: Ready for Review

#677 Add simple script for benchmark execution
  buildscripts/run_benchmarks.py
Labels: Ready for Review, Waiting on CI

#746 Update tests exec
  .travis.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/test.py
  buildscripts/utilities.py
Labels: Ready for Review, Waiting on CI

#749 Update build exec and clean up buildscripts
  .travis.yml
  buildscripts/azure/template-linux-macos.yml
  buildscripts/azure/template-windows.yml
  buildscripts/build.py
  buildscripts/numba-conda-recipe/LICENSE.txt
  buildscripts/numba-conda-recipe/README.md
  buildscripts/numba-conda-recipe/recipe/0001-Add-prange-variant-to-has_no_side_effect.patch
  buildscripts/numba-conda-recipe/recipe/0002-Add-test-for-prange-side-effect.patch
  buildscripts/numba-conda-recipe/recipe/0003-Line-length.patch
  buildscripts/numba-conda-recipe/recipe/bld.bat
  buildscripts/numba-conda-recipe/recipe/build.sh
  buildscripts/numba-conda-recipe/recipe/mandel.py
  buildscripts/numba-conda-recipe/recipe/meta.yaml
  buildscripts/numba-conda-recipe/recipe/run_test.bat
  buildscripts/numba-conda-recipe/recipe/run_test.sh
  buildscripts/utilities.py
Labels: Ready for Review, Waiting on CI

#687 correct doc for DF.median
  examples/dataframe/dataframe_median.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#688 correct doc for DF.mean
  examples/dataframe/dataframe_mean.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#691 correct doc for DF.prod
  examples/dataframe/dataframe_prod.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#756 Add scipy to doc build env to avoid examples failure
  buildscripts/build_doc.py
Labels: Ready to merge

#758 delete extension todo
  docs/source/for_developers.rst
  docs/source/other_intel_python_projects.rst
Labels: Ready to merge

#757 change limitations in str methods
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Ready to merge

#754 change doc for Series.nunique
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#753 correct doc for Series.cov
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#639 Series str ljust
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#700 correct doc for Series.str.lower
  examples/series/str/series_str_lower.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#755 Fix perf tests for df.rolling methods
  sdc/tests/tests_perf/test_perf_df_rolling.py
Labels: Ready to merge

#752 change doc for Series.corr
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/tests/test_series.py
Labels: Ready to merge

#692 correct doc for DF.std
  examples/dataframe/dataframe_std.py
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#768 Add generating of examples list
  docs/source/buildscripts/examples_generator.py
  docs/source/conf.py
  docs/source/examples.rst
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Documentation, Ready to merge

#765 Docs fix for external links
  docs/source/ext_links.txt
  docs/source/getting_started.rst
  docs/source/performance.rst
Labels: Ready to merge

#764 Add perf limitation
  sdc/datatypes/hpat_pandas_dataframe_functions.py
  sdc/datatypes/hpat_pandas_dataframe_rolling_functions.py
  sdc/datatypes/hpat_pandas_series_functions.py
  sdc/datatypes/hpat_pandas_series_rolling_functions.py
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Ready to merge

#763 Add Getting Started: What If I Get Poor Performance?
  docs/source/getting_started.rst
Labels: Ready to merge

#762 add docstring for DF.getitem
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#761 Add example to Basic Usage in doc
  buildscripts/run_examples.py
  docs/source/getting_started.rst
  examples/basic_usage_nyse_predict.py
Labels: Documentation, Ready to merge

#760 Add Getting Started: Measuring Performance
  docs/source/getting_started.rst
Labels: Ready to merge

#767 change check parameter to_strip
  sdc/datatypes/hpat_pandas_stringmethods_functions.py
Labels: Ready to merge

#775 Fix limitations in Series constructor
  sdc/hiframes/pd_series_ext.py
Labels: Documentation, Ready to merge, Waiting on CI

#759 Update compilation docs
  docs/source/getting_started.rst
  docs/source/workflow.rst
Labels: Ready for Review

#780 delete extension limitations
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#776 Fix warning about using nopython=True with ngit
  sdc/hiframes/pd_dataframe_ext.py
Labels: Ready to merge

#770 correct doc for Series.lt
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#773 Add note about numba version in readme.rst
  README.rst
Labels: Ready to merge

#784 Fix limitations line
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Documentation, Ready for Review

#778 correct doc for Series.median
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge

#787 Fix typos in docs/compilation
  docs/source/compilation.rst
Labels: Ready to merge

#779 Df doc fix
  sdc/datatypes/hpat_pandas_dataframe_functions.py
Labels: Ready to merge

#782 Groupby limitations
  sdc/datatypes/hpat_pandas_groupby_functions.py
Labels: Ready to merge

#774 Fix Series docs
  sdc/datatypes/hpat_pandas_series_functions.py
Labels: Ready to merge
